### ISSUE TITLE
New request page

### ISSUE THREAD

**Issue by noraatfedora** [jaredgoodman03/Minerva#75]
This should look similar to the old one with images.
There should be a description for each item.
After Joseph's email, it looks like the best way to go is just with checkboxes again, plus a textbox for things like household items. The textboxes should probably go in a "special requests" column of the orders table or something.

**Comment by agavram** [comment]
This should be reverting to the old page, but just with the new descriptions and images.

**Comment by noraatfedora** [comment]
ok this is dumb I'm gonna close this
